<a href="https://colab.research.google.com/github/Kim-Yeon-Jun/PyTorch/blob/main/SigPytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#텐서 연산시에 연산대상이 되는 텐서들은 같은 장치에 존재해야함
data = [
    [1,2],
    [3,4]
]

x = torch.tensor(data)
print(x.is_cuda)

x = x.cuda() #GPU로 데이터 옮기기
print(x.is_cuda)

x = x.cpu() #CPU로 데이터 옮기기
print(x.is_cuda)

False
True
False


In [ ]:
#행렬 곱 연산
#GPU 장치의 텐서
a = torch.tensor([
    [1,1],
    [2,2]
]).cuda()

b = torch.tensor([
    [5,6],
    [7,8]
])

#print(torch.matmul(a,b)) # 오류 발생
print(torch.matmul(a.cpu(), b))

tensor([[12, 14],
        [24, 28]])


In [ ]:
tensor = torch.rand(3,4)

print(tensor)
print(f"Shape: {tensor.shape}")
print(f"Data Type: {tensor.dtype}")
print(f"Device: {tensor.device}")

tensor([[0.1903, 0.6321, 0.0946, 0.6040],
        [0.4994, 0.9190, 0.9948, 0.1982],
        [0.7053, 0.3414, 0.2541, 0.9723]])
Shape: torch.Size([3, 4])
Data Type: torch.float32
Device: cpu


In [ ]:
#텐서 초기화
data = [
    [1,2],
    [3,4]
]
x = torch.tensor(data)

print(x)

tensor([[1, 2],
        [3, 4]])


In [ ]:
#넘파이 배열에서 텐서 초기화
a = torch.tensor([5])
b = torch.tensor([7])

c = (a+b).numpy()
print(c)
print(type(c))

result = c * 10
tensor = torch.from_numpy(result)
print(tensor)
print(type(tensor))

[12]
<class 'numpy.ndarray'>
tensor([120])
<class 'torch.Tensor'>


In [ ]:
#다른 텐서로부터 텐서 초기화
x = torch.tensor([
    [5,7],
    [1,2]
])

#x와 같은 모양과 자료형을 가지지만, 값이 1인 텐서 생성
x_ones = torch.ones_like(x)
print(x_ones)
#x와 같은 모양을 가지되, 자료형은 float으로 덮어쓰고, 값은 랜덤으로 채우기
x_rand = torch.rand_like(x, dtype=torch.float32) #uniform distribution [0, 1]
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9065, 0.9146],
        [0.5213, 0.5863]])


#텐서의 형변환 및 차원조작

In [ ]:
tensor = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(tensor[0]) # 첫번째 행
print(tensor[:, 0]) # 첫번째 열
print(tensor[..., -1]) # 마지막 열

tensor([1, 2, 3, 4])
tensor([1, 5, 9])
tensor([ 4,  8, 12])


In [ ]:
#텐서 이어붙이기
tensor = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

#dim : 텐서를 이어 붙이기 위한 축
# 0번 축(행)을 기준으로 이어 붙이기
result = torch.cat([tensor, tensor, tensor], dim=0)
print(result)

# 1번 축(행)을 기준으로 이어 붙이기
result = torch.cat([tensor, tensor, tensor], dim=1)
print(result)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])


In [ ]:
#텐서 형변환
a = torch.tensor([2], dtype=torch.int)
b = torch.tensor([5.0])

print(a.dtype)
print(b.dtype)

#텐서 a는 자동으로 float32형으로 형변환 처리
print(a+b)
#텐서 b는 int32형으로 형변환하여 덧셈 수행
print(a+b.type(torch.int32))

torch.int32
torch.float32
tensor([7.])
tensor([7], dtype=torch.int32)


In [ ]:
#텐서의 모양 변경 .. view()
#텐서의 순서는 변경되지 않음
a = torch.tensor([1,2,3,4,5,6,7,8])
b = a.view(4,2)
print(b)

#a의 값을 변경하면 b도 변경됨
a[0]=7
print(b)

#a의 값 을 복사한 뒤에 변경
c = a.clone().view(4,2)
a[0]=9
print(c)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
#텐서의 차원 교환
a = torch.rand((64, 32, 3))
print(a)
print(a.shape)
b = a.permute(2, 1, 0) # 차원 자체를 교환
#(2번째 축, 1번째 축, 0번째 축)
print(b.shape)

tensor([[[0.4431, 0.0766, 0.4185],
         [0.7519, 0.6603, 0.7285],
         [0.1817, 0.3559, 0.7952],
         ...,
         [0.0705, 0.4567, 0.3232],
         [0.6904, 0.6624, 0.0301],
         [0.2435, 0.6409, 0.8660]],

        [[0.7297, 0.1103, 0.8662],
         [0.8987, 0.0897, 0.3472],
         [0.6187, 0.6424, 0.1658],
         ...,
         [0.3011, 0.2714, 0.7780],
         [0.2340, 0.7292, 0.4790],
         [0.4403, 0.0569, 0.0147]],

        [[0.5527, 0.2839, 0.2310],
         [0.4034, 0.4828, 0.3624],
         [0.2814, 0.3563, 0.1069],
         ...,
         [0.9219, 0.7547, 0.7865],
         [0.1208, 0.8097, 0.2179],
         [0.0840, 0.1112, 0.7776]],

        ...,

        [[0.4246, 0.6468, 0.7615],
         [0.7861, 0.3174, 0.6323],
         [0.0696, 0.2789, 0.5260],
         ...,
         [0.5215, 0.9865, 0.5063],
         [0.5759, 0.6100, 0.2569],
         [0.3625, 0.2419, 0.4894]],

        [[0.6889, 0.1729, 0.0225],
         [0.4475, 0.9932, 0.6515],
         [0.

#텐서의 연산과 함수

In [ ]:
#같은 크기를 가진 두 개의 텐서에 대하여 사칙연산이 가능함
#기본적으로 요소별(element-wise) 연산
a = torch.tensor([
    [1,2],
    [3,4]
])
b = torch.tensor([
    [5,6],
    [7,8]
])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [ ]:
#행렬곱
a = torch.tensor([
    [1,2],
    [3,4]
])
b = torch.tensor([
    [5,6],
    [7,8]
])
print(a.matmul(b))
print(torch.matmul(a,b))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [ ]:
#평균함수
a = torch.Tensor([
    [1,2,3,4],
    [5,6,7,8]
])
print(a)
print(a.mean()) #전체원소
print(a.mean(dim=0)) # 각 열에 대한 평균
print(a.mean(dim=1)) # 각 행에 대한 평균

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(4.5000)
tensor([3., 4., 5., 6.])
tensor([2.5000, 6.5000])


In [ ]:
#합계함수
a = torch.Tensor([
    [1,2,3,4],
    [5,6,7,8]
])
print(a)
print(a.sum()) #전체원소
print(a.sum(dim=0)) # 각 열에 대한 합
print(a.sum(dim=1)) # 각 행에 대한 합

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(36.)
tensor([ 6.,  8., 10., 12.])
tensor([10., 26.])


In [ ]:
#텐서의 최대 함수
#max() : 원소의 최댓값 반환
#argmax() : 가장 큰 원소(최댓값)의 인덱스 반환
a = torch.Tensor([
    [1,2,3,4],
    [5,6,7,8]
])
print(a)
print(a.max())
print(a.max(dim=0))
print(a.max(dim=1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(8.)
torch.return_types.max(
values=tensor([5., 6., 7., 8.]),
indices=tensor([1, 1, 1, 1]))
torch.return_types.max(
values=tensor([4., 8.]),
indices=tensor([3, 3]))


In [ ]:
a = torch.Tensor([
    [1,2,3,4],
    [5,6,7,8]
])
print(a)
print(a.argmax())
print(a.argmax(dim=0))
print(a.argmax(dim=1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(7)
tensor([1, 1, 1, 1])
tensor([3, 3])


In [ ]:
#텐서의 차원 줄이기 / 늘리기
# unsqueeze() : 크기가 1인 차원을 추가함
# squeeze() : 크기가 1인 차원을 제거함
a = torch.Tensor([
    [1,2,3,4],
    [5,6,7,8]
])
print(a.shape)

#첫 번째 축에 차원 추가
a = a.unsqueeze(0)
print(a)
print(a.shape)

#네 번째 축에 차원 추가
a = a.unsqueeze(3)
print(a)
print(a.shape)

torch.Size([2, 4])
tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
torch.Size([1, 2, 4])
tensor([[[[1.],
          [2.],
          [3.],
          [4.]],

         [[5.],
          [6.],
          [7.],
          [8.]]]])
torch.Size([1, 2, 4, 1])


In [ ]:
a = a.squeeze()
print(a)
print(a.shape)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])


# 자동 미분과 기울기(Gradient)

In [ ]:
import torch

#requires_grad를 설정할 때만 기울기 추적
x = torch.tensor([3.0, 4.0], requires_grad = True)
y = torch.tensor([1.0, 2.0], requires_grad = True)
z = x + y

print(z)
print(z.grad_fn)

out = z.mean()
print(out)
print(out.grad_fn)

out.backward() # scalar에 대하여
print(x.grad)
print(y.grad)
print(z.grad) # leaf variable에 대해서만 gradient추적이 가능하다. 따라서 None

tensor([4., 6.], grad_fn=<AddBackward0>)
tensor(5., grad_fn=<MeanBackward0>)
tensor([0.5000, 0.5000])
tensor([0.5000, 0.5000])
None


<ipython-input-27-e4da87c83933>:18: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(z.grad) # leaf variable에 대해서만 gradient추적이 가능하다. 따라서 None


In [ ]:
# 일반적으로 모델을 학습할 때는 기울기를 추적함.
# 학습된 모델을 사용할 때는 파라미터를 업데이트 하지 않음. -> 기울기를 추적하지 않는 것이 일반적이다.

temp = torch.tensor([3.0, 4.0], requires_grad = True)
print(temp.requires_grad)
print((temp**2).requires_grad)

#기울기 추적x -> 계산속도가 더 빠름
with torch.no_grad():
  temp = torch.tensor([3.0, 4.0], requires_grad = True)
  print(temp.requires_grad)
  print((temp**2).requires_grad)

True
True
True
False
